=== akoimeexx/examples-xml/pkmn.xml.validator/pkmn.template.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xml:lang="EN">

<!-- "Attack/Pokemon Type" named simpleType definition -->
<xs:simpleType name="enum-type">
	<xs:annotation>
		<xs:documentation>Enumeration of Pokemon and Move element types</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string">
		<xs:enumeration value="normal" />
		<xs:enumeration value="fire" />
		<xs:enumeration value="water" />
		<xs:enumeration value="electric" />
		<xs:enumeration value="grass" />
		<xs:enumeration value="ice" />
		<xs:enumeration value="fight" />
		<xs:enumeration value="poison" />
		<xs:enumeration value="ground" />
		<xs:enumeration value="flying" />
		<xs:enumeration value="psychic" />
		<xs:enumeration value="bug" />
		<xs:enumeration value="rock" />
		<xs:enumeration value="ghost" />
		<xs:enumeration value="dragon" />
		<xs:enumeration value="dark" />
		<xs:enumeration value="steel" />
	</xs:restriction>
</xs:simpleType>
		
<!-- Pokemon element defining a pokemon roster object -->
<xs:element name="pokemon">
	<xs:complexType>
		<!-- Child elements -->
		<xs:all>
			<!-- Types element to store the pokemon type(s) -->
			<xs:element name="types" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<!-- Type element, with attribute for name  -->
						<xs:element name="type" minOccurs="1" maxOccurs="2">
							<xs:complexType>
								<xs:attribute name="name" type="enum-type" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Stats element to store Pokemon stat details-->
			<xs:element name="stats" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="stat" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="ev" default="0">
									<xs:simpleType>
										<xs:restriction base="xs:integer">
											<xs:minInclusive value="0" />
											<xs:maxInclusive value="255" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="iv" default="1">
									<xs:simpleType>
										<xs:restriction base="xs:positiveInteger">
											<xs:minInclusive value="1" />
											<xs:maxInclusive value="31" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="name" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="hp" />
											<xs:enumeration value="attack" />
											<xs:enumeration value="defense" />
											<xs:enumeration value="special attack" />
											<xs:enumeration value="special defense" />
											<xs:enumeration value="speed" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="value" type="xs:positiveInteger" default="1" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Moveset element to store a list of moves -->
			<xs:element name="moveset" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<!-- Move element, with attributes for name, style, and type -->
						<xs:element name="move" minOccurs="1" maxOccurs="4">
							<xs:complexType>
								<xs:attribute name="name" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="1" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="pp" type="xs:positiveInteger" use="required" />
								<xs:attribute name="style" default="physical">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="physical" />
											<xs:enumeration value="special" />
											<xs:enumeration value="status" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="type" type="enum-type" default="normal" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Optional element to display user-supplied notes -->
			<xs:element name="notes" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:all>

		<!-- Pokemon element attributes -->
	<!-- 
	     xsd: pokemon must have at least a dexid and name set if it has content any 
	     child elements set.
	-->
		<!--
		     xsd: ability, if set, must be an enum of available abilities.
		-->
		<xs:attribute name="ability" type="xs:string" />
		<xs:attribute name="dexid" default="0">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0" />
					<xs:maxInclusive value="649"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		
		<!-- Gender: [male|female] | unset -->
		<xs:attribute name="gender">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="male" />
					<xs:enumeration value="female" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<!-- 
		     xsd: item, if set, must be a string greater than zero in length.
		-->
		<xs:attribute name="item" type="xs:string" />
		
		<!-- Level: [1-100] | unset -->
		<xs:attribute name="level">
			<xs:simpleType>
				<xs:restriction base="xs:positiveInteger">
					<xs:maxInclusive value="100"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<!-- 
		     xsd: name, if set, must be the name of the kind of pokemon. The only way 
		     to 100% cover this is by using an enum of all current 'mons(600+ strings). 
		     Otherwise, must be a string greater than zero and less than or equal to 
		     ten in length.
		-->
		<xs:attribute name="name" type="xs:string" default="Missingno" />
		
		<!-- Nature: [enum-natures value] | unset -->
		<xs:attribute name="nature">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<!-- Neutral natures -->
					<xs:enumeration value="bashful" />
					<xs:enumeration value="docile" />
					<xs:enumeration value="hardy" />
					<xs:enumeration value="quirky" />
					<xs:enumeration value="serious" />
					<!-- Attack-boosting natures -->
					<xs:enumeration value="adamant" /><!-- Reduces Special Attack -->
					<xs:enumeration value="brave" /><!-- Reduces Speed -->
					<xs:enumeration value="lonely" /><!-- Reduces Defense -->
					<xs:enumeration value="naughty" /><!-- Reduces Special Defense -->
					<!-- Defense-boosting natures -->
					<xs:enumeration value="bold" /><!-- Reduces Attack -->
					<xs:enumeration value="impish" /><!-- Reduces Special Attack -->
					<xs:enumeration value="lax" /><!-- Reduces Special Defense -->
					<xs:enumeration value="relaxed" /><!-- Reduces Speed -->
					<!-- Speed-boosting natures -->
					<xs:enumeration value="hasty" /><!-- Reduces Defense -->
					<xs:enumeration value="jolly" /><!-- Reduces Special Attack -->
					<xs:enumeration value="naive" /><!-- Reduces Special Defense -->
					<xs:enumeration value="timid" /><!-- Reduces Attack -->
					<!-- Special Attack-boosting natures -->
					<xs:enumeration value="mild" /><!-- Reduces Defense -->
					<xs:enumeration value="modest" /><!-- Reduces Attack -->
					<xs:enumeration value="quiet" /><!-- Reduces Speed -->
					<xs:enumeration value="rash" /><!-- Reduces Special Defense -->
					<!-- Special Defense-boosting natures -->
					<xs:enumeration value="calm" /><!-- Reduces Attack -->
					<xs:enumeration value="careful" /><!-- Reduces Special Attack -->
					<xs:enumeration value="gentle" /><!-- Reduces Defense -->
					<xs:enumeration value="sassy" /><!-- Reduces Speed -->
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		
		<!-- Nickname: ([a-zA-Z0-9 _-]){1,10} | unset -->
		<xs:attribute name="nickname">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="([a-zA-Z0-9 _-]){1,10}" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		
		<!-- Shiny: [shiny] | unset -->
		<xs:attribute name="shiny">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="shiny" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:element>

</xs:schema>

=== akoimeexx/examples-xml/pkmn.xml.validator/blaziken.pkmn.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="pkmn.template.xsl"?>

<pokemon 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pkmn.template.xsd" 
	
	ability="Speed Boost" 
	dexid="257" 
	gender="male" 
	item="???" 
	level="100" 
	name="Blaziken" 
	nature="adamant" 
	nickname="Blaziken" 
	shiny="shiny">
	<types>
		<type name="fire" />
		<type name="fight" />
	</types>
	<moveset>
		<move name="Flare Blitz" pp="24" style="physical" type="fire" />
		<move name="Sky Uppercut" pp="24" style="physical" type="fight" />
		<move name="Brave Bird" pp="24" style="physical" type="flying" />
		<move name="Poison Jab" pp="32" style="physical" type="poison" />
	</moveset>
	<stats>
		<stat ev="255" iv="31" name="HP" value="999" />
		<stat ev="255" iv="31" name="Attack" value="999" />
		<stat ev="255" iv="31" name="Defense" value="999" />
		<stat ev="255" iv="31" name="Special Attack" value="999" />
		<stat ev="255" iv="31" name="Special Defense" value="999" />
		<stat ev="255" iv="31" name="Speed" value="999" />
	</stats>
	<notes></notes>
</pokemon>

=== akoimeexx/examples-xml/pkmn.xml.validator/missingno.pkmn.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="pkmn.template.xsl"?>

<pokemon 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pkmn.template.xsd" 
	
	ability="Sunder Game" 
	dexid="0" 
	item="Dubious Disc" 
	level="999" 
	name="Missingno" 
	nature="corrupted" 
	nickname="Missingno">
	<types>
		<type name="&lt;unset&gt;" />
		<type name="normal" />
		<type name="fire" />
		<type name="water" />
		<type name="electric" />
		<type name="grass" />
		<type name="ice" />
		<type name="fight" />
		<type name="poison" />
		<type name="ground" />
		<type name="flying" />
		<type name="psychic" />
		<type name="bug" />
		<type name="rock" />
		<type name="ghost" />
		<type name="dragon" />
		<type name="dark" />
		<type name="steel" />
	</types>
	<moveset>
		<move name="&lt;unset&gt;" pp="99" style="" type="" />
		<move name="Pound" pp="99" style="physical" type="normal" />
		<move name="Ember" pp="99" style="special" type="fire" />
		<move name="Bubble" pp="99" style="special" type="water" />
		<move name="Thundershock" pp="99" style="special" type="electric" />
		<move name="Vine Whip" pp="99" style="physical" type="grass" />
		<move name="Ice Beam" pp="99" style="special" type="ice" />
		<move name="Low Kick" pp="99" style="physical" type="fight" />
		<move name="Toxic" pp="99" style="special" type="poison" />
		<move name="Earthquake" pp="99" style="physical" type="ground" />
		<move name="Peck" pp="99" style="physical" type="flying" />
		<move name="Trick Room" pp="99" style="status" type="psychic" />
		<move name="Signal Beam" pp="99" style="special" type="bug" />
		<move name="Rock Tomb" pp="99" style="physical" type="rock" />
		<move name="Shadow Ball" pp="99" style="special" type="ghost" />
		<move name="Outrage" pp="99" style="physical" type="dragon" />
		<move name="Dark Pulse" pp="99" style="special" type="dark" />
		<move name="Steel Wing" pp="99" style="physical" type="steel" />
	</moveset>
	<stats>
		<stat ev="255" iv="31" name="HP" value="999" />
		<stat ev="255" iv="31" name="Attack" value="999" />
		<stat ev="255" iv="31" name="Defense" value="999" />
		<stat ev="255" iv="31" name="Special Attack" value="999" />
		<stat ev="255" iv="31" name="Special Defense" value="999" />
		<stat ev="255" iv="31" name="Speed" value="999" />
	</stats>
	<notes>Even when not a valid pkmn xml file (based on pkmn.template.xsd), this should still display reasonably correct in a browser. This file has an excess of child elements in its &lt;types&gt; and &lt;moveset&gt; elements. This file has wildly invalid values assigned to various attributes. Please review the xsd file for clarification.</notes>
</pokemon>

=== akoimeexx/examples-xml/pkmn.xml.validator/zoroark.pkmn.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="pkmn.template.xsl"?>

<pokemon 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pkmn.template.xsd" 
	
	ability="Illusion" 
	dexid="571" 
	gender="male" 
	item="???" 
	level="100" 
	name="Zoroark" 
	nature="modest" 
	nickname="Zoroark">
	<types>
		<type name="dark" />
	</types>
	<moveset>
		<move name="Night Daze" pp="16" style="special" type="dark" />
		<move name="Extrasensory" pp="48" style="special" type="psychic" />
		<move name="Flamethrower" pp="24" style="special" type="fire" />
		<move name="U-turn" pp="32" style="physical" type="bug" />
	</moveset>
	<stats>
		<stat ev="255" iv="31" name="HP" value="999" />
		<stat ev="255" iv="31" name="Attack" value="999" />
		<stat ev="255" iv="31" name="Defense" value="999" />
		<stat ev="255" iv="31" name="Special Attack" value="999" />
		<stat ev="255" iv="31" name="Special Defense" value="999" />
		<stat ev="255" iv="31" name="Speed" value="999" />
	</stats>
</pokemon>

=== akoimeexx/examples-xml/pkmn.xml.validator/mamoswine.pkmn.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="pkmn.template.xsl"?>

<pokemon 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="pkmn.template.xsd" 
	
	ability="Thick Fat" 
	dexid="473" 
	gender="male" 
	item="Expert Belt" 
	level="100" 
	name="Mamoswine" 
	nature="adamant" 
	nickname="Mamoswine">
	<types>
		<type name="ice" />
		<type name="ground" />
	</types>
	<moveset>
		<move name="Ice Fang" pp="24" style="physical" type="ice" />
		<move name="Ice Shard" pp="48" style="physical" type="ice" />
		<move name="Icicle Crash" pp="16" style="physical" type="ice" />
		<move name="Earthquake" pp="16" style="physical" type="ground" />
	</moveset>
	<stats>
		<stat ev="255" iv="31" name="HP" value="999" />
		<stat ev="255" iv="31" name="Attack" value="999" />
		<stat ev="255" iv="31" name="Defense" value="999" />
		<stat ev="255" iv="31" name="Special Attack" value="999" />
		<stat ev="255" iv="31" name="Special Defense" value="999" />
		<stat ev="255" iv="31" name="Speed" value="999" />
	</stats>
	<notes></notes>
</pokemon>
